export const DATABASE_SOURCE = 'DATABASE_SOURCE';
export const REPOSITORIES = {
  USERS: 'USERS_REPOSITORY',
  SESSIONS: 'SESSIONS_REPOSITORY',
};
export const MEDIA_CATEGORIES = {
  MOVIES: 'MOVIES',
  SERIES: 'SERIES',
};
